name: real_estate
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  icons_plus: ^5.0.0
  google_nav_bar: ^5.0.6
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.5.0
  firebase_core: ^2.30.1
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.4
  firebase_storage: ^11.7.4
  location: ^6.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
