name: real_estate
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  icons_plus: ^5.0.0
  google_nav_bar: ^5.0.6
  cupertino_icons: ^1.0.8
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  rxdart: ^0.27.7
  flutter_bloc: ^8.1.5
  intl: ^0.19.0
  gif: ^2.3.0
  video_player: ^2.8.6
  google_sign_in: ^6.2.1
  geolocator: ^12.0.0
  sliding_up_panel: ^2.0.0+1
  geocoding: ^3.0.0
  location: ^6.0.2
  google_maps_flutter: ^2.6.1
  firebase_auth: ^4.20.0
  firebase_app_check: ^0.2.2+7
  firebase_core: ^2.32.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/calculateGif.gif
