name: real_estate
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  icons_plus: ^5.0.0
  google_nav_bar: ^5.0.6
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.1
  location: ^6.0.1
  flutter_polyline_points: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
